spring:
  mongodb:
    uri: ${MONGO_CONNECTION_STRING}

  data:
    mongodb:
      auto-index-creation: ${AUTO_INDEX_CREATION:false}

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}