spring:
  mongodb:
    uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017/chat_db}

  data:
    mongodb:
      auto-index-creation: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/chat_api
    username: ${POSTGRES_USER:chat_api}
    password: ${POSTGRES_PASSWORD:admin123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:c2VjcmV0b2ZpY2lhbGNoYXRhcGljbGF2ZXNlY3JldGE=}
  expiration-ms: 3600000